name: Translate Readme

on:
  push:
    branches: ['**']

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 3

      - name: Auto Translate
        uses: Lin-jun-xiang/action-translate-readme@v2
        with:
          token: ${{ secrets.PAT_PROTOSSDRAGOON_FOR_ACTIONBOT }}
          g4f_provider: g4f.Provider.DeepAi # You can change this provider
          langs: "zh-CN,en"
